config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  root "profiles#feed"

  resources :profiles, only: [:index, :show]
  
  get "feed", to: "profiles#feed", as: :feed 
  
  post "follow/:id", to: "follows#follow", as: :follow
  post "like/:id", to: "likes#like", as: :like 
  resources :posts, only: [:new, :create, :show, :destroy, :update, :edit] do
    
    resources :comments, only: [:create, :destroy]
    
  end

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post
  belongs_to :user

  validates :body, presence:true
  include Visible 
end

app/models/concerns/Visible.rb
module Visible   extend ActiveSupport::Concern
    def author?(cur_user)
      cur_user == self.user
    end
end

app/models/post.rb
class Post < ApplicationRecord

    include ImageUploader::Attachment(:image)
    include Visible 
    belongs_to :user
    has_many :comments, dependent: :delete_all
    has_and_belongs_to_many :liked_users, class_name: "User", join_table: "likes"

    validates :image, presence: true
    validates :body, presence: true
  end

app/models/user.rb
class User < ApplicationRecord
  followability
  has_many :posts
  has_many :comments

  has_and_belongs_to_many :liked_posts, class_name: "Post", join_table: "likes"

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable


  validates :username, uniqueness: true

  attr_writer :login

  def login
    @login = self.username || self.email
  end
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
  
  def follow(user)
    self.send_follow_request_to(user)
    user.accept_follow_request_of(self)
  end

  def unfollow(user)
    self.followerable_relationships.where(followable_id: user.id).destroy_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:username, :firstname, :lastname, :password])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params.merge(user_id: current_user.id))
      if @comment.save
        redirect_to post_path(@post)
      else
        flash[:notice] = "you can't create comments without text"
        redirect_to post_path(@post)
      end

    end

    def destroy
      @comment = Comment.find(params[:id])
      if current_user.comments.exists?(@comment.id)
        Comment.delete(@comment.id)
      else
        flash[:notice] = "you can't delete comments that aren't yours"
      end
      redirect_to post_path(@comment.post), status: 303
    end

    private
      def comment_params
        params.require(:comment).permit(:commenter, :body)
      end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  protect_from_forgery except: [:follow]
  before_action :find_user
  def follow
     current_user.following?(@user) ? current_user.unfollow(@user) : current_user.follow(@user)
    respond_to :js
end

private
  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    protect_from_forgery except: [:like]
    def like
        if !@post.liked_users.exists?(current_user.id)
            @post.liked_users.push(current_user)
        else
            @post.liked_users.delete(current_user)
        end
        respond_to :js
    end

private
    def find_post
        @post = Post.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def show
        @post = Post.find(params[:id])

    end

    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.build(post_params)

        if @post.save
            redirect_to post_path(@post)
        else 
            render :new
        end 
    end
    

    def edit
        @post = current_user.posts.find(params[:id])
    end

    def update
        @post = current_user.posts.find(params[:id])
        if  @post.update(post_params)
            redirect_to post_path(@post)
        else 
            render :edit
        end 
    end



    def destroy
        if  @post = current_user.posts.find(params[:id])
            @post.destroy
        end
        
        redirect_to feed_path
    end    





    private
    def post_params
        params.require(:post).permit(:body, :image, :status, :liked_users)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user  = User.find(params[:id])
  end

  def feed
    @posts = Post.where("user_id IN (?) OR user_id = ?", current_user.following_ids, current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.erb
  <b> <%= comment.user.username%></b>: <%= comment.body %>
 
  <%if comment.author?(current_user)%>
    <%= link_to "Destroy", [comment.post, comment], data: {
                  method: :delete,
                  confirm: "Are you sure?"
                  } %>
  <% end %>
  <br>

app/views/comments/_comment.html.erb
  <b> <%= comment.user.username%></b>: <div><%= comment.body %></div>
 
  <%if comment.author?(current_user)%>
    <%= link_to "Destroy", [comment.post, comment], data: {
                  method: :delete,
                  confirm: "Are you sure?"
                  } %>
  <% end %>
  <br>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
 <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <br>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/follows/follow.js.erb
<% if current_user.following?(@user) %>
    $('#follow_button').html("<%= escape_javascript(button_to 'Unfollow', follow_path(@user), method: :post, remote: true, id: 'follow_button') %>");
    $('#followers_count').html("<%= j @user.followers.count %>");
<% else %>
    $('#follow_button').html("<%= escape_javascript(button_to 'Follow', follow_path(@user), method: :post, remote: true, id: 'follow_button') %>");
    $('#followers_count').html("<%= j @user.followers.count %>");  
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar">
      <%= link_to "Feed", feed_path %>
      <%= link_to "All users", profiles_path %>
      <%= link_to "New post", new_post_path %>
      <% if user_signed_in?%>
      <%= link_to "My profile", profile_path(current_user) %>
      
      
        <div class="signout">
        
          <%= link_to "exit", destroy_user_session_path, data: { turbo_method: :delete } %>
          </div>
        <% end %> 
        
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CdgCourseProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/header" %>
      <%= yield %>
   
  </body>
</html>

app/views/likes/like.js.erb
<%if !@post.liked_users.exists?(current_user.id)%>
$("#like_button[data-like-post-id='<%=@post.id%>']").html("<%= escape_javascript(button_to 'like', like_path(@post), remote: true, method: :post, id: 'like_button') %>");
$("#like-count[data-post-id='<%=@post.id%>']").html("<%= j @post.liked_users.count %>");
<%else%>
$("#like_button[data-like-post-id='<%=@post.id%>']").html("<%= escape_javascript(button_to 'unlike', like_path(@post), remote: true, method: :post, id: 'like_button') %>");
$("#like-count[data-post-id='<%=@post.id%>']").html("<%= j @post.liked_users.count %>");
<%end%>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
  <div>
    <%= form.label :image %><br>
     <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="w-[500px] m-auto mt-16">

        <div class="px-2""><%=link_to post.user.username,  profile_path(post.user)%></div>
        
            <%= image_tag post.image_url, class:"h-[500px] w-[500px] rounded-[6px] mt-3"%>
        <div class="ml-1" >

            <div class="mt-3 px-2 flex flex-row h-[42px]">
            <div id="like_button" data-like-post-id="<%= post.id%>">
                <%if post.liked_users.exists?(current_user.id)%>
                    <%= button_to "unlike", like_path(post), remote: true, method: :post%>
                <%else%>
                    <%= button_to "like", like_path(post), remote: true, method: :post%>
                <%end%>
            </div>
                <br>
            <div class="flex flex-row ml-5">
                 
                 <div id="like-count" data-post-id="<%= post.id %>">
                     likes: <%= post.liked_users.count %>
                </div> 
                </div>
            </div>    
        
                    
            <div class="font-bold">
                <%= post.user.username%>
            </div> 
            <%=  post.body %>
            <div class="text-gray-500 mt-1"><%= link_to "all comments (#{post.comments.count})", post %></div>
            <div class="text-gray-500 mt-1 text-[13px]"><%= post.created_at%>.</div>
        </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form", post: @post %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= render "posts/post", post: @post %>
<div class="w-[500px] m-auto mt-16">
    <%= link_to "Back", feed_path, class:"ml-3"  %>
    <%if @post.author?(current_user)%>
    <%= link_to "Edit", edit_post_path(@post)%>
    <%= link_to "Destroy", post_path(@post), class:"ml-3" ,  data: {
                  method: :delete,
                  confirm: "Are you sure?"
                }%>
    <%end%>

    <div class="mt-5">
        <%if !(@post.comments.empty?)%>
        <div>Comments:</div>
            <%= render @post.comments %>
        <%else%>
            <div> Noone coment yet </div>
        <%end%>
    </div>
    <div class="mt-5">Add a comment:</div>
        <%= render 'comments/form' %>
    <div> 
<div> 

app/views/profiles/_follow_button.html.erb
<% if current_user.following?(user)%>
    <%= button_to "Unfollow", follow_path(user), method: :post, remote: true, id: "follow_button"%>
<% else-%>
    <%= button_to "Follow", follow_path(user), method: :post, remote: true, id: "follow_button"%>
<% end%>

app/views/profiles/feed.html.erb
<% @posts.reverse.each do |post| %>

<%= render "posts/post", post: post %>

<% end %>

app/views/profiles/index.html.erb
<% @users.each do |user| %>
    <%=link_to user.email , profile_path(user)%><br>
<% end%>

app/views/profiles/show.html.erb
<div class="px-10">
    <%= @user.email%><br>
    <div class="flex flex-row">
        
        <div class="flex flex-row ">followers:<div id="followers_count"><%= @user.followers.count%></div></div>
        <div class="flex flex-row ml-5">followings:<div id="following_count"><%= @user.following.count%></div></div>
    </div>
    <% if !(@user.id == current_user.id)%> <%= render "follow_button", user: @user%> <%end%>
    

<%if !(@user.posts.empty?)%>
    <div class="mt-5">user posts:</div>
    <div class=" w-[700px] flex flex-row ">
    
        <% @user.posts.each do |post|%>
            <div>
                <%= link_to post do %>
                    <%= image_tag post.image_url, class: "h-[150px] w-[150px] ml-3 mt-2" %>
                <% end %>
            </div>
        <%end%>
    <%end%>
    </div>
</div>